[versions]
agp = "8.3.0"
gitPlugin = "3.0.0"

[libraries]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
git = { id = "com.palantir.git-version", version.ref = "gitPlugin" }

